### ISSUE TITLE
Access the revisions page without superuser access

### ISSUE THREAD

**Issue by fedme** [david-szabo97/grav-plugin-admin-addon-revisions#8]
Hi,
is it possible to have the revisions page in the admin panel even if the logged user doesn not have the  super user permission?
```
access:
  admin:
    login: true
    super: true // some of my admin users don't have this
```

Is there a special permission that allows me to do something like:
```
access:
  admin:
    login: true
    revisions: true
```
Thank you very much

**Comment by fedme** [comment]
Found the solution, just add the following to the user account:
```
access:
  admin:
    login: true
    revisions: true
```

It works due to how Grav builds the admin menu
